"""LoRA fine-tuning of the local cleanup model on correction pairs.

Uses PEFT + transformers (optional ``wisperfree[finetune]`` extra). The
adapter is merged and exported as a GGUF-ready directory, plus an Ollama
Modelfile so the tuned model can be registered locally with:

    ollama create wisperfree-tuned -f <output>/Modelfile

Everything runs on-device; nothing is uploaded anywhere.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from wisperfree.config import FinetuneConfig

log = logging.getLogger(__name__)


def train_lora(config: FinetuneConfig, dataset_path: Path, output_dir: Path) -> Path:
    """Run a LoRA fine-tune; returns the adapter directory."""
    try:
        import torch
        from datasets import load_dataset
        from peft import LoraConfig, get_peft_model
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            Trainer,
            TrainingArguments,
        )
    except ImportError as exc:
        raise RuntimeError(
            "Fine-tuning dependencies missing; install wisperfree[finetune]"
        ) from exc

    output_dir.mkdir(parents=True, exist_ok=True)
    tokenizer = AutoTokenizer.from_pretrained(config.base_model)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        config.base_model,
        torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
        device_map="auto",
    )
    lora = LoraConfig(
        r=config.lora_r,
        lora_alpha=config.lora_alpha,
        lora_dropout=config.lora_dropout,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora)

    dataset = load_dataset("json", data_files=str(dataset_path), split="train")

    def tokenize(example):
        text = tokenizer.apply_chat_template(
            example["messages"], tokenize=False, add_generation_prompt=False
        )
        tokens = tokenizer(
            text,
            truncation=True,
            max_length=config.max_seq_len,
            padding="max_length",
        )
        tokens["labels"] = tokens["input_ids"].copy()
        return tokens

    tokenized = dataset.map(tokenize, remove_columns=dataset.column_names)

    args = TrainingArguments(
        output_dir=str(output_dir / "checkpoints"),
        num_train_epochs=config.epochs,
        per_device_train_batch_size=config.batch_size,
        learning_rate=config.learning_rate,
        logging_steps=5,
        save_strategy="no",
        report_to=[],
    )
    Trainer(model=model, args=args, train_dataset=tokenized).train()

    adapter_dir = output_dir / "adapter"
    model.save_pretrained(str(adapter_dir))
    tokenizer.save_pretrained(str(adapter_dir))
    write_modelfile(config, output_dir, adapter_dir)
    return adapter_dir


def write_modelfile(
    config: FinetuneConfig, output_dir: Path, adapter_dir: Path
) -> Path:
    """Emit an Ollama Modelfile that layers the LoRA adapter on the base."""
    modelfile = output_dir / "Modelfile"
    base = config.base_model.rsplit("/", 1)[-1].lower()
    modelfile.write_text(
        "\n".join(
            [
                f"# Generated by WisperFree — register with:",
                f"#   ollama create {config.ollama_output_model} -f {modelfile}",
                f"FROM {base}",
                f"ADAPTER {adapter_dir}",
                'PARAMETER temperature 0.1',
                "",
            ]
        )
    )
    meta = output_dir / "training_meta.json"
    meta.write_text(json.dumps({"base_model": config.base_model}, indent=2))
    return modelfile
